name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:

  docker:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: '6.4.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v4.2.0
        id: version_step # step id used as a reference for output values
        with:
          updateProjectFiles: true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build only
        uses: docker/build-push-action@v6
        with:
          if: github.event.pull_request.base.ref == 'main'
          platforms: linux/amd64,linux/arm64
          context: "./src"
          file: "./src/OnkelMato.BlogEngine.Web/Dockerfile"
          push: false

      - name: Build and push nightly
        uses: docker/build-push-action@v6
        with:
          if: startsWith(github.ref, 'refs/heads/main')
          platforms: linux/amd64,linux/arm64
          context: "./src"
          file: "./src/OnkelMato.BlogEngine.Web/Dockerfile"
          push: true
          tags: thomasley/onkelmatoblogengineweb:latest

      - name: Build and push tag
        uses: docker/build-push-action@v6
        with:
          if: github.ref_type == 'tag'
          platforms: linux/amd64,linux/arm64
          context: "./src"
          file: "./src/OnkelMato.BlogEngine.Web/Dockerfile"
          push: true
          tags: thomasley/onkelmatoblogengineweb:${{ steps.version_step.outputs.majorMinorPatch }}
